spring:
  cloud:
    config:
      server:
        git:
          #uri: C:\work\ksr\kolkata2020labsconfig
          uri: https://github.com/prabhakarmishra/Newboot.git
          #searchPaths: ConfigData
          skipSslValidation: true
    bus:
      enabled: true
      destination: configXchangebus
  rabbitmq:
    host: 192.168.99.101
    port: 5672

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: '*'